version: "3"
services:
  altv:
    image: daschaos/altv:release
    container_name: altv
    volumes:
      - data:/altv-persistend/
    ports:
      - "7788:7788"
      - "7788:7788/udp"
volumes:
  data:
